version: '3'
services:
backend:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - MONGODB_URI=mongodb+srv://Sanyam632000:Snp632000@cluster0.rl9zf.mongodb.net/Users?retryWrites=true&w=majority
    ports:
      - "3030:3030"
